# -*- coding: utf-8 -*-
"""Compressive Sensing para Estimação de Harmônicos e Interharmônicos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SoVsibx0dVhpLFnpjFgNBR0ZGd-0OUcI

# **Algoritmo CoSaMP com a dct**
"""

# !pip install codecarbon

"""#**Algoritmo CoSaMP com a dct**"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.fftpack import dct, idct
from codecarbon import OfflineEmissionsTracker

# Funções de métrica
def calculate_prd(original, reconstructed):
    return np.sqrt(np.sum((original - reconstructed) ** 2)) / np.sqrt(np.sum(original ** 2)) * 100

def calculate_rmse(original, reconstructed):
    return np.sqrt(np.mean((original - reconstructed) ** 2))

# Iniciando o tracker de emissões <- CODECARBON
tracker = OfflineEmissionsTracker(country_iso_code="BRA", output_file='emissions_CoSaMP_com_dct.csv')

print("cosamp, dct")

# Parâmetros do sinal
Fs = 10240       # Frequência de amostragem
Ts = 1 / Fs     # Período de amostragem
t = np.arange(Fs) * Ts  # Vetor de tempo
f = 60          # Frequência fundamental (Hz)

# Sinal harmônico com componentes ímpares
harm = [1, 3, 7, 15, 27, 35, 45]
y = np.sum([(1/h) * np.cos(2 * np.pi * h * f * t) for h in harm], axis=0)

# sinal original
original_dct = 2*np.abs(np.fft.fft(y, norm='ortho'))/len(y)
#dct(y, norm='ortho')

# Adição de ruído gaussiano
SNR_dB = 40  # Razão sinal-ruído em dB
ruido = np.random.normal(0, np.sqrt(np.var(y)/(10 ** (SNR_dB / 10))), len(y))
y_ruidoso = y + ruido

# Iniciando a medição das emissões
tracker.start()

# Compressive Sensing
CR = 50  # Taxa de compressão (60%)
N = len(y)
M = int(N * (100 - CR) / 100)  # Número de medidas

# Algoritmo CoSaMP verdadeiro
def cosamp(Phi, y, K, max_iter=10, tol=1e-5):
    residual = y.copy()
    idx = np.array([], dtype=int)
    x = np.zeros(Phi.shape[1], dtype=complex)

    for _ in range(max_iter):
        proxy = Phi.conj().T @ residual
        omega = np.argsort(np.abs(proxy))[-2*K:]
        idx = np.union1d(idx, omega).astype(int)
        Phi_selected = Phi[:, idx]
        b, _, _, _ = np.linalg.lstsq(Phi_selected, y, rcond=None)

        # Prune
        idx_new = np.argsort(np.abs(b))[-K:]
        idx = idx[idx_new]
        x_temp = np.zeros(Phi.shape[1], dtype=complex)
        x_temp[idx] = b[idx_new]
        residual = y - Phi @ x_temp

        if np.linalg.norm(residual) < tol:
            break
    return x_temp

"""
# Algoritmo COSAMP (1 iteração por chamada)
def cosamp(A, s, num_coefs=40):

    r = s.copy()
    correlations = np.abs(A.T @ r)
    idx = np.argsort(correlations)[-2*num_coefs:]  # Seleciona 2*num_coefs candidatos
    A_selected = A[:, idx]
    x_selected = np.linalg.lstsq(A_selected, s, rcond=None)[0]

    # Mantém apenas os maiores coeficientes
    idx_top = np.argsort(np.abs(x_selected))[-num_coefs:]
    x = np.zeros(A.shape[1])
    x[idx[idx_top]] = x_selected[idx_top]

    return x
"""
# Execução do experimento (200 iterações)
n_iterations = 5
prd_values = np.zeros(n_iterations)
prd_noisy_values = np.zeros(n_iterations)
rmse_values = np.zeros(n_iterations)
rmse_noisy_values = np.zeros(n_iterations)
harmonic_errors = np.zeros((n_iterations, len(harm)))

for i in range(n_iterations):
    print(f"Iteração {i+1}/{n_iterations}")
    # Amostragem aleatória diferente a cada iteração
    samples = np.random.choice(N, M, replace=False)
    samples.sort()

    # Matriz de medição (DCT subamostrada)
    A = dct(np.eye(N), norm='ortho')[samples, :]

    # Medições com e sem ruído
    clean_measurements = y[samples]
    noisy_measurements = y_ruidoso[samples]

    # Reconstrução com COSAMP (1 iteração)
    # Reconstrução do sinal limpo (para comparação)
    coeffs_clean = cosamp(A, clean_measurements, K=14)
    reconstructed_clean = idct(coeffs_clean, norm='ortho')
    reconstructed_clean = reconstructed_clean * (np.max(y) / np.max(reconstructed_clean))

    # Reconstrução do sinal ruidoso
    coeffs_noisy = cosamp(A, noisy_measurements, K=14)
    reconstructed_noisy = idct(coeffs_noisy, norm='ortho')
    #reconstructed_noisy = reconstructed_noisy #* (np.max(y_ruidoso) / np.max(reconstructed_noisy))

    # Cálculo das métricas
    prd_values[i] = calculate_prd(y, reconstructed_clean)
    prd_noisy_values[i] = calculate_prd(y, reconstructed_noisy)  # Comparando com o original sem ruído
    rmse_values[i] = calculate_rmse(y, reconstructed_clean)
    rmse_noisy_values[i] = calculate_rmse(y, reconstructed_noisy)

    # Erros nas harmônicas (usando a reconstrução ruidosa)
    recon_dct = 2*np.abs(np.fft.fft(reconstructed_noisy, norm='ortho'))/len(reconstructed_noisy)
    #for j, h in enumerate(harm):
    for j in range(len(harm)):
        #idx_h = int(h * f * N / Fs)
        idx_h = (int(harm[j]) * f/(Fs/N))
        #idx_h = (idx_h).astype(int)
        harmonic_errors[i, j] = 100*(np.abs(original_dct[(int(idx_h))]) - np.abs(recon_dct[(int(idx_h))]))/np.abs(original_dct[(int(idx_h))])

# Encerrando as leituras de emissões
emissions: float = tracker.stop()

# Resultados finais
print("\nResultados para o sinal SEM ruído na entrada:")
print(f"PRD médio: {np.mean(prd_values):.2f}% ± {np.std(prd_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_values):.4f} ± {np.std(rmse_values):.4f}")

print("\nResultados para o sinal COM ruído (SNR = 20dB):")
print(f"PRD médio: {np.mean(prd_noisy_values):.2f}% ± {np.std(prd_noisy_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_noisy_values):.4f} ± {np.std(rmse_noisy_values):.4f}")
print("\nErros médios nas harmônicas (com ruído):")
for j, h in enumerate(harm):
    print(f"Harmônica {h}: {np.mean(harmonic_errors[:, j]):.4f} ± {np.std(harmonic_errors[:, j]):.4f}")

# Plot dos sinais

# Sinal de ruído inserido
ruido_inserido = y_ruidoso - y

# Plot do sinal original
plt.figure(figsize=(12, 4))
plt.plot(t, y, label='Original', color='red')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do ruído inserido
plt.figure(figsize=(12, 4))
plt.plot(t, ruido_inserido, label='Ruído Inserido', color='gray')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Ruído Inserido no Sinal')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do sinal reconstruído
plt.figure(figsize=(12, 4))
plt.plot(t, reconstructed_noisy, label='Reconstruído com ruído', linestyle='--', color='blue')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title(f'Sinal Reconstruído (CoSaMP + DCT, CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Espectro de Frequência (FFT) - Original
freq = np.fft.fftfreq(N, Ts)[:N//2]
fft_y = 2/N * np.abs(np.fft.fft(y)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_y, label='Original ', color='red')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Espectro de Frequência (FFT) - Reconstruído
fft_rec = 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_rec, '--', label='Reconstruído ', color='blue')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Reconstruído')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

"""
# Plot do sinal original
plt.figure(figsize=(12, 4))
plt.plot(t, y, label='Original', color='red')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do sinal ruidoso
#plt.figure(figsize=(12, 4))
#plt.plot(t, y_ruidoso, label=f'Ruidoso (SNR={SNR_dB}dB)', color='orange')
#plt.xlabel('Tempo (s)')
#plt.ylabel('Amplitude')
#plt.title('Sinal Ruidoso')
#plt.grid()
#plt.legend()
#plt.tight_layout()
##plt.show()

# Plot do sinal reconstruído
plt.figure(figsize=(12, 4))
plt.plot(t, reconstructed_noisy, label='Reconstruído com ruído', linestyle='--', color='blue')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title(f'Sinal Reconstruído (CoSaMP + DCT, CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

"""
"""
# (Opcional) Comparação dos 3 sinais
plt.figure(figsize=(12, 5))
plt.plot(t, y, label='Original', color='black', linewidth=1)
plt.plot(t, y_ruidoso, label='Ruidoso', alpha=0.5, color='orange')
plt.plot(t, reconstructed_noisy, '--', label='Reconstruído', color='blue')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Comparação dos Sinais')
plt.legend()
plt.grid()
plt.tight_layout()
#plt.show()

"""
"""
# Espectro de Frequência (FFT)
freq = np.fft.fftfreq(N, Ts)[:N//2]
plt.figure(figsize=(12, 6))
plt.plot(freq, 2/N * np.abs(np.fft.fft(y)[0:N//2]), label='Original (FFT)')
plt.plot(freq, 2/N * np.abs(np.fft.fft(y_ruidoso)[0:N//2]), alpha=0.7, label='Ruidoso (FFT)')
plt.plot(freq, 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2]), '--', label='Reconstruído (FFT)')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência')
plt.legend()
plt.grid()
plt.tight_layout()
#plt.show()
"""

# Print das emissões geradas
print(f'Emissões geradas pelo algoritmo de CS: {emissions} Kg')

import numpy as np
import matplotlib.pyplot as plt


# Parâmetros do sinal
Fs = 10240       # Frequência de amostragem
Ts = 1 / Fs     # Período de amostragem
t = np.arange(Fs) * Ts  # Vetor de tempo
f = 60          # Frequência fundamental (Hz)

# Sinal harmônico com componentes ímpares
harm = [1, 3, 7, 15, 27, 35, 45]
y = np.sum([(1/h) * np.cos(2 * np.pi * h * f * t) for h in harm], axis=0)
plt.plot(y[0:256])

import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft, ifft
from codecarbon import OfflineEmissionsTracker

print("cosamp real, DFT ajustado")

# Funções de métrica
def calculate_prd(original, reconstructed):
    return np.sqrt(np.sum((original - reconstructed) ** 2)) / np.sqrt(np.sum(original ** 2)) * 100

def calculate_rmse(original, reconstructed):
    return np.sqrt(np.mean((original - reconstructed) ** 2))

# Iniciando o tracker de emissões <- CODECARBON
tracker = OfflineEmissionsTracker(country_iso_code="BRA", output_file='emissions_CoSaMP_com_dft.csv')

# Parâmetros do sinal
Fs = 10240
Ts = 1 / Fs
t = np.arange(Fs) * Ts
f = 60

harm = [1, 3, 7, 15, 27, 35, 45]
y = np.sum([(1/h) * np.cos(2 * np.pi * h * f * t) for h in harm], axis=0)

# DFT do sinal original
original_dft = np.abs(fft(y)) / len(y)

# Adição de ruído
SNR_dB = 40
ruido = np.random.normal(0, np.sqrt(np.var(y)/(10 ** (SNR_dB / 10))), len(y))
y_ruidoso = y + ruido

# Parâmetros de compressão
CR = 50
N = len(y)
M = int(N * (100 - CR) / 100)

# Matriz DFT explícita
def create_dft_matrix(N):
    n = np.arange(N)
    k = n.reshape((N, 1))
    W = np.exp(-2j * np.pi * k * n / N) / np.sqrt(N)
    return W

# Algoritmo CoSaMP verdadeiro
def cosamp(Phi, y, K, max_iter=10, tol=1e-5):
    residual = y.copy()
    idx = np.array([], dtype=int)
    x = np.zeros(Phi.shape[1], dtype=complex)

    for _ in range(max_iter):
        proxy = Phi.conj().T @ residual
        omega = np.argsort(np.abs(proxy))[-2*K:]
        idx = np.union1d(idx, omega).astype(int)
        Phi_selected = Phi[:, idx]
        b, _, _, _ = np.linalg.lstsq(Phi_selected, y, rcond=None)

        # Prune
        idx_new = np.argsort(np.abs(b))[-K:]
        idx = idx[idx_new]
        x_temp = np.zeros(Phi.shape[1], dtype=complex)
        x_temp[idx] = b[idx_new]
        residual = y - Phi @ x_temp

        if np.linalg.norm(residual) < tol:
            break
    return x_temp

# Iniciando a medição das emissões
tracker.start()

# Execução do experimento
n_iterations = 5
prd_values = np.zeros(n_iterations)
prd_noisy_values = np.zeros(n_iterations)
rmse_values = np.zeros(n_iterations)
rmse_noisy_values = np.zeros(n_iterations)
harmonic_errors = np.zeros((n_iterations, len(harm)))

F = create_dft_matrix(N)  # matriz DFT completa

for i in range(n_iterations):
    print(f"Iteração {i+1}/{n_iterations}")

    samples = np.random.choice(N, M, replace=False)
    samples.sort()

    Phi = F[samples, :]

    clean_measurements = y[samples]
    noisy_measurements = y_ruidoso[samples]

    coeffs_clean = cosamp(Phi, clean_measurements, K=14)
    reconstructed_clean = ifft(coeffs_clean * np.sqrt(N)).real  # ifft normalizado

    coeffs_noisy = cosamp(Phi, noisy_measurements, K=14)
    reconstructed_noisy = ifft(coeffs_noisy * np.sqrt(N)).real

    # Normalização opcional para comparar forma de onda
    reconstructed_clean *= (np.max(y) / np.max(reconstructed_clean))
    reconstructed_noisy *= (np.max(y) / np.max(reconstructed_noisy))

    # Métricas
    prd_values[i] = calculate_prd(y, reconstructed_clean)
    prd_noisy_values[i] = calculate_prd(y, reconstructed_noisy)
    rmse_values[i] = calculate_rmse(y, reconstructed_clean)
    rmse_noisy_values[i] = calculate_rmse(y, reconstructed_noisy)

    # Erros nas harmônicas
    recon_dft = np.abs(fft(reconstructed_noisy))/len(reconstructed_noisy)
    for j in range(len(harm)):
        idx_h = int(harm[j] * f * N / Fs)
        harmonic_errors[i, j] = 100 * np.abs(np.abs(original_dft[idx_h]) - np.abs(recon_dft[idx_h])) / np.abs(original_dft[idx_h])

# Encerrando as leituras de emissões
emissions: float = tracker.stop()

# Resultados
print("\nResultados para o sinal SEM ruído:")
print(f"PRD médio: {np.mean(prd_values):.2f}% ± {np.std(prd_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_values):.4f} ± {np.std(rmse_values):.4f}")

print("\nResultados para o sinal COM ruído:")
print(f"PRD médio: {np.mean(prd_noisy_values):.2f}% ± {np.std(prd_noisy_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_noisy_values):.4f} ± {np.std(rmse_noisy_values):.4f}")

print("\nErros médios nas harmônicas (com ruído):")
for j, h in enumerate(harm):
    print(f"Harmônica {h}: {np.mean(harmonic_errors[:, j]):.4f} ± {np.std(harmonic_errors[:, j]):.4f}")


# Plot dos sinais

# Sinal de ruído inserido
ruido_inserido = y_ruidoso - y

# Plot do sinal original
plt.figure(figsize=(12, 4))
plt.plot(t, y, label='Original', color='red')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do ruído inserido
plt.figure(figsize=(12, 4))
plt.plot(t, ruido_inserido, label='Ruído Inserido', color='gray')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Ruído Inserido no Sinal')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do sinal reconstruído
plt.figure(figsize=(12, 4))
plt.plot(t, reconstructed_noisy, label='Reconstruído com ruído', linestyle='--', color='blue')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title(f'Sinal Reconstruído (CoSaMP + DFT, CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Espectro de Frequência (FFT) - Original
freq = np.fft.fftfreq(N, Ts)[:N//2]
fft_y = 2/N * np.abs(np.fft.fft(y)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_y, label='Original', color='red')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Espectro de Frequência (FFT) - Reconstruído
fft_rec = 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_rec, '--', label='Reconstruído', color='blue')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Reconstruído')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()
"""
# Plot dos sinais
plt.figure(figsize=(12, 8))

plt.subplot(2, 1, 1)
plt.plot(t, ruido, alpha=0.7, label=f'Ruído (SNR={SNR_dB}dB)')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title('Ruído')
plt.grid()

plt.subplot(2, 1, 2)
plt.plot(t, reconstructed_noisy, '--', label='Reconstruído com ruído')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title(f'Reconstrução via CoSaMP+DFT (CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()

plt.tight_layout()
#plt.show()

# Plot do espectro DFT
freq = np.fft.fftfreq(N, Ts)[:N//2]
plt.figure(figsize=(12, 6))
plt.plot(freq, 2/N * np.abs(fft(y)[:N//2]), label='Original (DFT)')
plt.plot(freq, 2/N * np.abs(fft(y_ruidoso)[:N//2]), alpha=0.7, label='Ruidoso (DFT)')
plt.plot(freq, 2/N * np.abs(fft(reconstructed_noisy)[:N//2]), '--', label='Reconstruído (DFT)')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência (DFT)')
plt.legend()
plt.grid()
#plt.show()

"""
# Print das emissões geradas
print(f'Emissões geradas pelo algoritmo de CS: {emissions} Kg')

"""# **Algoritmo OMP com a dct**"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.fftpack import dct, idct
from codecarbon import OfflineEmissionsTracker

print("Algoritmo OMP com DCT")

# Iniciando o tracker de emissões <- CODECARBON
tracker = OfflineEmissionsTracker(country_iso_code="BRA", output_file='emissions_OMP_com_dct.csv')

# Funções de métrica (mantidas as mesmas)
def calculate_prd(original, reconstructed):
    return np.sqrt(np.sum((original - reconstructed) ** 2)) / np.sqrt(np.sum(original ** 2)) * 100

def calculate_rmse(original, reconstructed):
    return np.sqrt(np.mean((original - reconstructed) ** 2))

# Parâmetros do sinal (mantidos os mesmos)
Fs = 10240       # Frequência de amostragem
Ts = 1 / Fs     # Período de amostragem
t = np.arange(Fs) * Ts  # Vetor de tempo
f = 60          # Frequência fundamental (Hz)

# Sinal harmônico com componentes ímpares
harm = [1, 3, 7, 15, 27, 35, 45]
y = np.sum([(1/h) * np.cos(2 * np.pi * h * f * t) for h in harm], axis=0)

# DCT do sinal original
original_dct = 2*np.abs(np.fft.fft(y, norm='ortho'))/len(y)

# Adição de ruído gaussiano
SNR_dB = 40  # Razão sinal-ruído em dB
ruido = np.random.normal(0, np.sqrt(np.var(y)/(10 ** (SNR_dB / 10))), len(y))
y_ruidoso = y + ruido

# Compressive Sensing
CR = 50  # Taxa de compressão (50%)
N = len(y)
M = int(N * (100 - CR) / 100)  # Número de medidas

# Algoritmo OMP (Orthogonal Matching Pursuit)
def omp(A, y, k):
    """
    Implementação do OMP para recuperação esparsa

    Parâmetros:
    A : Matriz de medição (M x N)
    y : Vetor de medidas (M x 1)
    k : Número esperado de coeficientes não nulos

    Retorna:
    x : Vetor esparso estimado (N x 1)
    """
    m, n = A.shape
    x = np.zeros(n)
    residual = y.copy()
    support = []

    for _ in range(k):
        # Passo 1: Encontrar o átomo mais correlacionado com o resíduo
        correlations = np.abs(A.T @ residual)
        correlations[support] = 0  # Ignorar átomos já selecionados
        new_idx = np.argmax(correlations)

        # Passo 2: Adicionar ao suporte
        support.append(new_idx)

        # Passo 3: Resolver mínimos quadrados com os átomos selecionados
        A_support = A[:, support]
        x_support = np.linalg.lstsq(A_support, y, rcond=None)[0]

        # Passo 4: Atualizar a solução e o resíduo
        x.fill(0)
        x[support] = x_support
        residual = y - A @ x

    return x

# Iniciando a medição das emissões
tracker.start()

# Execução do experimento (5 iterações)
n_iterations = 5
prd_values = np.zeros(n_iterations)
prd_noisy_values = np.zeros(n_iterations)
rmse_values = np.zeros(n_iterations)
rmse_noisy_values = np.zeros(n_iterations)
harmonic_errors = np.zeros((n_iterations, len(harm)))

for i in range(n_iterations):
    print(f"Iteração {i+1}/{n_iterations}")
    # Amostragem aleatória diferente a cada iteração
    samples = np.random.choice(N, M, replace=False)
    samples.sort()

    # Matriz de medição (DCT subamostrada)
    A = dct(np.eye(N), norm='ortho')[samples, :]

    # Medições com e sem ruído
    clean_measurements = y[samples]
    noisy_measurements = y_ruidoso[samples]

    # Reconstrução com OMP (k=14 coeficientes não nulos)
    # Reconstrução do sinal limpo (para comparação)
    coeffs_clean = omp(A, clean_measurements, k=14)
    reconstructed_clean = idct(coeffs_clean, norm='ortho')
    reconstructed_clean = reconstructed_clean * (np.max(y) / np.max(reconstructed_clean))

    # Reconstrução do sinal ruidoso
    coeffs_noisy = omp(A, noisy_measurements, k=14)
    reconstructed_noisy = idct(coeffs_noisy, norm='ortho')

    # Cálculo das métricas
    prd_values[i] = calculate_prd(y, reconstructed_clean)
    prd_noisy_values[i] = calculate_prd(y, reconstructed_noisy)  # Comparando com o original sem ruído
    rmse_values[i] = calculate_rmse(y, reconstructed_clean)
    rmse_noisy_values[i] = calculate_rmse(y, reconstructed_noisy)

    # Erros nas harmônicas (usando a reconstrução ruidosa)
    recon_dct = 2*np.abs(np.fft.fft(reconstructed_noisy, norm='ortho'))/len(reconstructed_noisy)
    for j in range(len(harm)):
        idx_h = (int(harm[j]) * f/(Fs/N))
        harmonic_errors[i, j] = 100*(np.abs(original_dct[(int(idx_h))]) - np.abs(recon_dct[(int(idx_h))]))/np.abs(original_dct[(int(idx_h))])

# Encerrando as leituras de emissões
emissions: float = tracker.stop()

# Resultados finais
print("\nResultados para o sinal SEM ruído na entrada:")
print(f"PRD médio: {np.mean(prd_values):.2f}% ± {np.std(prd_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_values):.4f} ± {np.std(rmse_values):.4f}")

print("\nResultados para o sinal COM ruído (SNR = 40dB):")
print(f"PRD médio: {np.mean(prd_noisy_values):.2f}% ± {np.std(prd_noisy_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_noisy_values):.4f} ± {np.std(rmse_noisy_values):.4f}")
print("\nErros médios nas harmônicas (com ruído):")
for j, h in enumerate(harm):
    print(f"Harmônica {h}: {np.mean(harmonic_errors[:, j]):.4f} ± {np.std(harmonic_errors[:, j]):.4f}")


# Plot dos sinais

# Sinal de ruído inserido
ruido_inserido = y_ruidoso - y

# Plot do sinal original
plt.figure(figsize=(12, 4))
plt.plot(t, y, label='Original', color='red')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do ruído inserido
plt.figure(figsize=(12, 4))
plt.plot(t, ruido_inserido, label='Ruído Inserido', color='gray')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Ruído Inserido no Sinal')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do sinal reconstruído
plt.figure(figsize=(12, 4))
plt.plot(t, reconstructed_noisy, label='Reconstruído com ruído', linestyle='--', color='blue')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title(f'Sinal Reconstruído (OMP + DCT, CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Espectro de Frequência (FFT) - Original
freq = np.fft.fftfreq(N, Ts)[:N//2]
fft_y = 2/N * np.abs(np.fft.fft(y)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_y, label='Original', color='red')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Espectro de Frequência (FFT) - Reconstruído
fft_rec = 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_rec, '--', label='Reconstruído', color='blue')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Reconstruído')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

"""
# Plot dos sinais
plt.figure(figsize=(12, 8))

# Sinal original vs ruidoso
plt.subplot(2, 1, 1)
plt.plot(t, ruido, alpha=0.7, label=f'Ruidoso (SNR={SNR_dB}dB)')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title('Sinal com Ruído')
plt.grid()

# Sinal original vs reconstruído com ruído
plt.subplot(2, 1, 2)
plt.plot(t, reconstructed_noisy, '--', label='Reconstruído com ruído')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title(f'Reconstrução com DCT e OMP (CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()

plt.tight_layout()
#plt.show()

# Plot do espectro DCT
freq = np.fft.fftfreq(N, Ts)[:N//2]
plt.figure(figsize=(12, 6))
plt.plot(freq, 2/N * np.abs(np.fft.fft(y)[0:N//2]), label='Original (FFT)')
plt.plot(freq, 2/N * np.abs(np.fft.fft(y_ruidoso)[0:N//2]), alpha=0.7, label='Ruidoso (FFT)')
plt.plot(freq, 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2]), '--', label='Reconstruído (FFT)')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência (para comparação)')
plt.legend()
plt.grid()
#plt.show()

"""
# Print das emissões geradas
print(f'Emissões geradas pelo algoritmo de CS: {emissions} Kg')

"""#**Algoritmo OMP com a dft**"""

import numpy as np
import matplotlib.pyplot as plt
from codecarbon import OfflineEmissionsTracker

print("Algoritmo OMP com DFT")

# Iniciando o tracker de emissões <- CODECARBON
tracker = OfflineEmissionsTracker(country_iso_code="BRA", output_file='emissions_OMP_com_dft_1.csv')

# Funções de métrica
def calculate_prd(original, reconstructed):
    return np.sqrt(np.sum((original - reconstructed) ** 2)) / np.sqrt(np.sum(original ** 2)) * 100

def calculate_rmse(original, reconstructed):
    return np.sqrt(np.mean((original - reconstructed) ** 2))

# Parâmetros do sinal
Fs = 10240
Ts = 1 / Fs
t = np.arange(Fs) * Ts
f = 60

# Sinal harmônico com componentes ímpares
harm = [1, 3, 7, 15, 27, 35, 45]
y = np.sum([(1/h) * np.cos(2 * np.pi * h * f * t) for h in harm], axis=0)

# DFT do sinal original
original_dft = 2*np.abs(np.fft.fft(y))/len(y)

# Adição de ruído gaussiano
SNR_dB = 40
ruido = np.random.normal(0, np.sqrt(np.var(y)/(10 ** (SNR_dB / 10))), len(y))
y_ruidoso = y + ruido

# Compressive Sensing
CR = 50
N = len(y)
M = int(N * (100 - CR) / 100)

# OMP
def omp(A, y, k):
    m, n = A.shape
    x = np.zeros(n, dtype=complex)
    residual = y.copy()
    support = []

    for _ in range(k):
        correlations = np.abs(A.T.conj() @ residual)
        correlations[support] = 0
        new_idx = np.argmax(correlations)
        support.append(new_idx)

        A_support = A[:, support]
        x_support = np.linalg.lstsq(A_support, y, rcond=None)[0]

        x.fill(0)
        x[support] = x_support
        residual = y - A @ x

    return x

# Iniciando a medição das emissões
tracker.start()

# Experimento
n_iterations = 5
prd_values = np.zeros(n_iterations)
prd_noisy_values = np.zeros(n_iterations)
rmse_values = np.zeros(n_iterations)
rmse_noisy_values = np.zeros(n_iterations)
harmonic_errors = np.zeros((n_iterations, len(harm)))

# Matriz base DFT (completa)
F = np.fft.fft(np.eye(N)) / np.sqrt(N)

for i in range(n_iterations):
    print(f"Iteração {i+1}/{n_iterations}")
    samples = np.random.choice(N, M, replace=False)
    samples.sort()

    A = F[samples, :]

    clean_measurements = y[samples]
    noisy_measurements = y_ruidoso[samples]

    coeffs_clean = omp(A, clean_measurements, k=14)
    reconstructed_clean = np.real(np.fft.ifft(coeffs_clean) * np.sqrt(N))
    reconstructed_clean *= np.max(y) / np.max(reconstructed_clean)

    coeffs_noisy = omp(A, noisy_measurements, k=14)
    reconstructed_noisy = np.real(np.fft.ifft(coeffs_noisy) * np.sqrt(N))

    prd_values[i] = calculate_prd(y, reconstructed_clean)
    prd_noisy_values[i] = calculate_prd(y, reconstructed_noisy)
    rmse_values[i] = calculate_rmse(y, reconstructed_clean)
    rmse_noisy_values[i] = calculate_rmse(y, reconstructed_noisy)

    recon_dft = 2*np.abs(np.fft.fft(reconstructed_noisy))/len(reconstructed_noisy)
    for j in range(len(harm)):
        idx_h = int(harm[j] * f / (Fs/N))
        harmonic_errors[i, j] = 100 * (np.abs(original_dft[idx_h]) - np.abs(recon_dft[idx_h])) / np.abs(original_dft[idx_h])

# Encerrando as leituras de emissões
emissions: float = tracker.stop()

# Resultados
print("\nResultados para o sinal SEM ruído na entrada:")
print(f"PRD médio: {np.mean(prd_values):.2f}% ± {np.std(prd_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_values):.4f} ± {np.std(rmse_values):.4f}")

print("\nResultados para o sinal COM ruído (SNR = 40dB):")
print(f"PRD médio: {np.mean(prd_noisy_values):.2f}% ± {np.std(prd_noisy_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_noisy_values):.4f} ± {np.std(rmse_noisy_values):.4f}")
print("\nErros médios nas harmônicas (com ruído):")
for j, h in enumerate(harm):
    print(f"Harmônica {h}: {np.mean(harmonic_errors[:, j]):.4f} ± {np.std(harmonic_errors[:, j]):.4f}")


# Plot dos sinais

# Sinal de ruído inserido
ruido_inserido = y_ruidoso - y

# Plot do sinal original
plt.figure(figsize=(12, 4))
plt.plot(t, y, label='Original', color='red')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do ruído inserido
plt.figure(figsize=(12, 4))
plt.plot(t, ruido_inserido, label='Ruído Inserido', color='gray')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Ruído Inserido no Sinal')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do sinal reconstruído
plt.figure(figsize=(12, 4))
plt.plot(t, reconstructed_noisy, label='Reconstruído com ruído', linestyle='--', color='blue')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title(f'Sinal Reconstruído (CoSaMP + DFT, CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Espectro de Frequência (FFT) - Original
freq = np.fft.fftfreq(N, Ts)[:N//2]
fft_y = 2/N * np.abs(np.fft.fft(y)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_y, label='Original ', color='red')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Espectro de Frequência (FFT) - Reconstruído
fft_rec = 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_rec, '--', label='Reconstruído', color='blue')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Reconstruído')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()
"""
# Plot
plt.figure(figsize=(12, 8))

plt.subplot(2, 1, 1)
plt.plot(t, ruido, alpha=0.7, label=f'Ruidoso (SNR={SNR_dB}dB)')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title('Sinal com Ruído')
plt.grid()

plt.subplot(2, 1, 2)
plt.plot(t, reconstructed_noisy, '--', label='Reconstruído com ruído')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title(f'Reconstrução com DFT e OMP (CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()

plt.tight_layout()
#plt.show()

freq = np.fft.fftfreq(N, Ts)[:N//2]
plt.figure(figsize=(12, 6))
plt.plot(freq, 2/N * np.abs(np.fft.fft(y)[0:N//2]), label='Original (FFT)')
plt.plot(freq, 2/N * np.abs(np.fft.fft(y_ruidoso)[0:N//2]), alpha=0.7, label='Ruidoso (FFT)')
plt.plot(freq, 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2]), '--', label='Reconstruído (FFT)')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência (para comparação)')
plt.legend()
plt.grid()
#plt.show()

"""
# Print das emissões geradas
print(f'Emissões geradas pelo algoritmo de CS: {emissions} Kg')

"""# **Algotimo SL0 com a dft**"""

import numpy as np
import matplotlib.pyplot as plt
from math import exp
from codecarbon import OfflineEmissionsTracker

# Iniciando o tracker de emissões <- CODECARBON
tracker = OfflineEmissionsTracker(country_iso_code="BRA", output_file='emissions_OMP_com_dft_2.csv')

# Funções de métrica (mantidas iguais)
def calculate_prd(original, reconstructed):
    return np.sqrt(np.sum((original - reconstructed) ** 2)) / np.sqrt(np.sum(original ** 2)) * 100

def calculate_rmse(original, reconstructed):
    return np.sqrt(np.mean((original - reconstructed) ** 2))

# Implementação do SL0 (adaptada)
# sigma_min= [0.1, 0.01, 0.5, 0.001]
# sigma_decrease_factor= [0.5]
# mu_0= [2, ] <- Pesquisar
# L= [1, 2, 3, 4, 5]

def sl0(A, y_compressed, sigma_min=0.1, sigma_decrease_factor=0.5, mu_0=2, L=1):
    """
    SL0 adaptado para seu sinal harmônico
    """
    A_pinv = np.linalg.pinv(A)
    s = A_pinv @ y_compressed
    sigma = 2.0 * np.abs(s).max()

    while sigma > sigma_min:
        for _ in range(L):
            delta = s * np.exp(-np.abs(s)**2 / sigma**2)
            s = s - mu_0 * delta
            s = s - A_pinv @ (A @ s - y_compressed)
        sigma *= sigma_decrease_factor

    return s

# --- Parâmetros do sinal (seus parâmetros originais) ---
Fs = 10240
Ts = 1 / Fs
t = np.arange(Fs) * Ts
f = 60  # Frequência fundamental
harm = [1, 3, 7, 15, 27, 35, 45]  # Componentes harmônicas ímpares

# Geração do sinal original
y = np.sum([(1/h) * np.cos(2 * np.pi * h * f * t) for h in harm], axis=0)
original_dft = 2*np.abs(np.fft.fft(y))/len(y)

# Adição de ruído (SNR = 40dB)
SNR_dB = 40
ruido = np.random.normal(0, np.sqrt(np.var(y)/(10 ** (SNR_dB / 10))), len(y))
y_ruidoso = y + ruido

# --- Compressive Sensing ---
CR = 50  # Taxa de compressão (50%)
N = len(y)
M = int(N * (100 - CR) / 100)

# Matriz base DFT (normalizada)
F = np.fft.fft(np.eye(N)) / np.sqrt(N)

# Iniciando a medição das emissões
tracker.start()

# --- Experimento Principal ---
n_iterations = 1
prd_values = np.zeros(n_iterations)
harmonic_errors = np.zeros((n_iterations, len(harm)))

for i in range(n_iterations):
    print(f"Iteração {i+1}/{n_iterations}")

    # Seleciona amostras aleatórias
    samples = np.random.choice(N, M, replace=False)
    samples.sort()

    # Cria matriz de medição
    A = F[samples, :]
    noisy_measurements = y_ruidoso[samples]

    # Executa SL0 adaptado
    coeffs_sl0 = sl0(A, noisy_measurements)

    # Reconstrução do sinal
    reconstructed = np.real(np.fft.ifft(coeffs_sl0) * np.sqrt(N))

    # Cálculo das métricas
    prd_values[i] = calculate_prd(y, reconstructed)

    # Análise espectral
    recon_dft = 2*np.abs(np.fft.fft(reconstructed))/len(reconstructed)
    for j, h in enumerate(harm):
        idx_h = int(h * f / (Fs/N))
        harmonic_errors[i,j] = 100*np.abs(original_dft[idx_h]-recon_dft[idx_h])/original_dft[idx_h]

# Encerrando as leituras de emissões
emissions: float = tracker.stop()

# --- Resultados ---
print("\n=== Resultados ===")
print(f"PRD médio: {np.mean(prd_values):.2f}% ± {np.std(prd_values):.2f}%")
print("\nErros médios nas harmônicas:")
for j, h in enumerate(harm):
    print(f"Harmônica {h}: {np.mean(harmonic_errors[:,j]):.2f}% ± {np.std(harmonic_errors[:,j]):.2f}%")

# Plot dos sinais

# Plot dos sinais

# Sinal de ruído inserido
ruido_inserido = y_ruidoso - y

# Plot do sinal original
plt.figure(figsize=(12, 4))
plt.plot(t, y, label='Original', color='red')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do ruído inserido
plt.figure(figsize=(12, 4))
plt.plot(t, ruido_inserido, label='Ruído Inserido', color='gray')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Ruído Inserido no Sinal')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do sinal reconstruído
plt.figure(figsize=(12, 4))
plt.plot(t, reconstructed_noisy, label='Reconstruído com ruído', linestyle='--', color='blue')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title(f'Sinal Reconstruído (CoSaMP + DFT, CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Espectro de Frequência (FFT) - Original
freq = np.fft.fftfreq(N, Ts)[:N//2]
fft_y = 2/N * np.abs(np.fft.fft(y)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_y, label='Original ', color='red')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Espectro de Frequência (FFT) - Reconstruído
fft_rec = 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_rec, '--', label='Reconstruído', color='blue')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Reconstruído')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()
"""
# Sinal de ruído inserido
ruido_inserido = y_ruidoso - y

# Plot do sinal original
plt.figure(figsize=(12, 4))
plt.plot(t, y, label='Original', color='red')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do ruído inserido
plt.figure(figsize=(12, 4))
plt.plot(t, ruido_inserido, label='Ruído Inserido', color='gray')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Ruído Inserido no Sinal')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Plot do sinal reconstruído
plt.figure(figsize=(12, 4))
plt.plot(t, reconstructed_noisy, label='Reconstruído com ruído', linestyle='--', color='blue')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title(f'Sinal Reconstruído (SL0 ) + DFT, CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Espectro de Frequência (FFT) - Original
freq = np.fft.fftfreq(N, Ts)[:N//2]
fft_y = 2/N * np.abs(np.fft.fft(y)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_y, label='Original ', color='red')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Espectro de Frequência (FFT) - Reconstruído
fft_rec = 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_rec, '--', label='Reconstruído', color='blue')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Reconstruído')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()


# --- Visualização ---
plt.figure(figsize=(12,8))
plt.subplot(2,1,1)
plt.plot(t, y, label='Original')
plt.plot(t, y_ruidoso, alpha=0.6, label='Com ruído')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title('Sinal Original e com Ruído (SNR=40dB)')
plt.grid()

plt.subplot(2,1,2)
plt.plot(t, reconstructed, 'r--', label='Reconstruído (SL0)')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title(f'Reconstrução com SL0 (CR={CR}%, PRD={np.mean(prd_values):.2f}%)')
plt.grid()
plt.tight_layout()

# Espectro de frequência
freq = np.fft.fftfreq(N, Ts)[:N//2]
plt.figure(figsize=(12,6))
plt.plot(freq, original_dft[:N//2], label='Original')
plt.plot(freq, recon_dft[:N//2], 'r--', label='SL0')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência')
plt.legend()
plt.grid()
#plt.show()

"""
# Print das emissões geradas
print(f'Emissões geradas pelo algoritmo de CS: {emissions} Kg')

import numpy as np
import matplotlib.pyplot as plt
from math import exp
from codecarbon import OfflineEmissionsTracker

# Iniciando o tracker de emissões <- CODECARBON
tracker = OfflineEmissionsTracker(country_iso_code="BRA", output_file='emissions_OMP_com_dft_3.csv')

# Funções de métrica
def calculate_prd(original, reconstructed):
    return np.sqrt(np.sum((original - reconstructed) ** 2)) / np.sqrt(np.sum(original ** 2)) * 100

def calculate_rmse(original, reconstructed):
    return np.sqrt(np.mean((original - reconstructed) ** 2))

# Implementação do SL0 (adaptada)
def sl0(A, y_compressed, sigma_min=0.1, sigma_decrease_factor=0.5, mu_0=2, L=1):
    """
    SL0 adaptado para seu sinal harmônico
    """
    A_pinv = np.linalg.pinv(A)
    s = A_pinv @ y_compressed
    sigma = 2.0 * np.abs(s).max()

    while sigma > sigma_min:
        for _ in range(L):
            delta = s * np.exp(-np.abs(s)**2 / sigma**2)
            s = s - mu_0 * delta
            s = s - A_pinv @ (A @ s - y_compressed)
        sigma *= sigma_decrease_factor

    return s

# --- Parâmetros do sinal ---
Fs = 10240
Ts = 1 / Fs
t = np.arange(Fs) * Ts
f = 60  # Frequência fundamental
harm = [1, 3, 7, 15, 27, 35, 45]  # Componentes harmônicas ímpares

# Geração do sinal original
y = np.sum([(1/h) * np.cos(2 * np.pi * h * f * t) for h in harm], axis=0)
original_dft = 2*np.abs(np.fft.fft(y))/len(y)

# Adição de ruído (SNR = 40dB)
SNR_dB = 40
ruido = np.random.normal(0, np.sqrt(np.var(y)/(10 ** (SNR_dB / 10))), len(y))
y_ruidoso = y + ruido

# --- Compressive Sensing ---
CR = 50  # Taxa de compressão (50%)
N = len(y)
M = int(N * (100 - CR) / 100)

# Matriz base DFT (normalizada)
F = np.fft.fft(np.eye(N)) / np.sqrt(N)

# Iniciando a medição das emissões
tracker.start()

# --- Experimento Principal ---
n_iterations = 5
prd_values = np.zeros(n_iterations)
rmse_values = np.zeros(n_iterations)
prd_noisy_values = np.zeros(n_iterations)
rmse_noisy_values = np.zeros(n_iterations)
harmonic_errors = np.zeros((n_iterations, len(harm)))

for i in range(n_iterations):
    print(f"Iteração {i+1}/{n_iterations}")

    # Seleciona amostras aleatórias
    samples = np.random.choice(N, M, replace=False)
    samples.sort()

    # Cria matriz de medição
    A = F[samples, :]
    clean_measurements = y[samples]
    noisy_measurements = y_ruidoso[samples]

    # Executa SL0 para medições limpas
    coeffs_clean = sl0(A, clean_measurements)
    reconstructed_clean = np.real(np.fft.ifft(coeffs_clean) * np.sqrt(N))
    reconstructed_clean *= np.max(y) / np.max(reconstructed_clean)  # Normalização

    # Executa SL0 para medições ruidosas
    coeffs_noisy = sl0(A, noisy_measurements)
    reconstructed_noisy = np.real(np.fft.ifft(coeffs_noisy) * np.sqrt(N))

    # Cálculo das métricas
    prd_values[i] = calculate_prd(y, reconstructed_clean)
    rmse_values[i] = calculate_rmse(y, reconstructed_clean)
    prd_noisy_values[i] = calculate_prd(y, reconstructed_noisy)
    rmse_noisy_values[i] = calculate_rmse(y, reconstructed_noisy)

    # Análise espectral
    recon_dft = 2*np.abs(np.fft.fft(reconstructed_noisy))/len(reconstructed_noisy)
    for j, h in enumerate(harm):
        idx_h = int(h * f / (Fs/N))
        harmonic_errors[i,j] = 100*np.abs(original_dft[idx_h]-recon_dft[idx_h])/original_dft[idx_h]

# Encerrando as leituras de emissões
emissions: float = tracker.stop()

# --- Resultados ---
print("\n=== Resultados ===")
print("Resultados para o sinal SEM ruído na entrada:")
print(f"PRD médio: {np.mean(prd_values):.2f}% ± {np.std(prd_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_values):.4f} ± {np.std(rmse_values):.4f}")
print("\nResultados para o sinal COM ruído (SNR = 40dB):")
print(f"PRD médio: {np.mean(prd_noisy_values):.2f}% ± {np.std(prd_noisy_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_noisy_values):.4f} ± {np.std(rmse_noisy_values):.4f}")
print("\nErros médios nas harmônicas (com ruído):")
for j, h in enumerate(harm):
    print(f"Harmônica {h}: {np.mean(harmonic_errors[:,j]):.2f}% ± {np.std(harmonic_errors[:,j]):.2f}%")

# --- Visualização ---
plt.figure(figsize=(12,8))
plt.subplot(2,1,1)
plt.plot(t, y, label='Original')
plt.plot(t, y_ruidoso, alpha=0.6, label='Com ruído')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title('Sinal Original e com Ruído (SNR=40dB)')
plt.grid()

plt.subplot(2,1,2)
plt.plot(t, reconstructed_noisy, 'r--', label='Reconstruído (SL0)')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title(f'Reconstrução com SL0 (CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.tight_layout()

# Espectro de frequência
freq = np.fft.fftfreq(N, Ts)[:N//2]
plt.figure(figsize=(12,6))
plt.plot(freq, original_dft[:N//2], label='Original')
plt.plot(freq, recon_dft[:N//2], 'r--', label='SL0')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência')
plt.legend()
plt.grid()
#plt.show()

# Print das emissões geradas
print(f'Emissões geradas pelo algoritmo de CS: {emissions} Kg')

"""#**Algoritmo SL0 com a dct**"""

import numpy as np
import matplotlib.pyplot as plt
from math import exp
from codecarbon import OfflineEmissionsTracker
from scipy.fft import dct, idct

# Iniciando o tracker de emissões
tracker = OfflineEmissionsTracker(country_iso_code="BRA", output_file='emissions_OMP_com_dct_3.csv')

# Funções de métrica
def calculate_prd(original, reconstructed):
    return np.sqrt(np.sum((original - reconstructed) ** 2)) / np.sqrt(np.sum(original ** 2)) * 100

def calculate_rmse(original, reconstructed):
    return np.sqrt(np.mean((original - reconstructed) ** 2))

# Implementação do SL0 (adaptada para DCT)
def sl0(A, y_compressed, sigma_min=0.1, sigma_decrease_factor=0.5, mu_0=2, L=1):
    """
    SL0 adaptado para DCT
    """
    A_pinv = np.linalg.pinv(A)
    s = A_pinv @ y_compressed
    sigma = 2.0 * np.abs(s).max()

    while sigma > sigma_min:
        for _ in range(L):
            delta = s * np.exp(-np.abs(s)**2 / sigma**2)
            s = s - mu_0 * delta
            s = s - A_pinv @ (A @ s - y_compressed)
        sigma *= sigma_decrease_factor

    return s

# --- Parâmetros do sinal ---
Fs = 10240
Ts = 1 / Fs
t = np.arange(Fs) * Ts
f = 60  # Frequência fundamental
harm = [1, 3, 7, 15, 27, 35, 45]  # Componentes harmônicas ímpares

# Geração do sinal original
y = np.sum([(1/h) * np.cos(2 * np.pi * h * f * t) for h in harm], axis=0)
original_dct = dct(y, norm='ortho')  # DCT do sinal original

# Adição de ruído (SNR = 40dB)
SNR_dB = 40
ruido = np.random.normal(0, np.sqrt(np.var(y)/(10 ** (SNR_dB / 10))), len(y))
y_ruidoso = y + ruido

# --- Compressive Sensing ---
CR = 50  # Taxa de compressão (50%)
N = len(y)
M = int(N * (100 - CR) / 100)

# Matriz base DCT (normalizada)
F = np.array([dct(np.eye(N)[i], norm='ortho') for i in range(N)]).T  # DCT matrix

# Iniciando a medição das emissões
tracker.start()

# --- Experimento Principal ---
n_iterations = 5
prd_values = np.zeros(n_iterations)
rmse_values = np.zeros(n_iterations)
prd_noisy_values = np.zeros(n_iterations)
rmse_noisy_values = np.zeros(n_iterations)
harmonic_errors = np.zeros((n_iterations, len(harm)))

for i in range(n_iterations):
    print(f"Iteração {i+1}/{n_iterations}")

    # Seleciona amostras aleatórias
    samples = np.random.choice(N, M, replace=False)
    samples.sort()

    # Cria matriz de medição
    A = F[samples, :]
    clean_measurements = y[samples]
    noisy_measurements = y_ruidoso[samples]

    # Executa SL0 para medições limpas
    coeffs_clean = sl0(A, clean_measurements)
    reconstructed_clean = idct(coeffs_clean, norm='ortho')  # Reconstrução com IDCT
    reconstructed_clean *= np.max(y) / np.max(reconstructed_clean)  # Normalização

    # Executa SL0 para medições ruidosas
    coeffs_noisy = sl0(A, noisy_measurements)
    reconstructed_noisy = idct(coeffs_noisy, norm='ortho')  # Reconstrução com IDCT

    # Cálculo das métricas
    prd_values[i] = calculate_prd(y, reconstructed_clean)
    rmse_values[i] = calculate_rmse(y, reconstructed_clean)
    prd_noisy_values[i] = calculate_prd(y, reconstructed_noisy)
    rmse_noisy_values[i] = calculate_rmse(y, reconstructed_noisy)

    # Análise espectral (usando DCT para o espectro reconstruído)
    recon_dct = dct(reconstructed_noisy, norm='ortho')
    for j, h in enumerate(harm):
        idx_h = int(h * f / (Fs/N))
        harmonic_errors[i,j] = 100 * np.abs(original_dct[idx_h] - recon_dct[idx_h]) / np.abs(original_dct[idx_h])

# Encerrando as leituras de emissões
emissions = tracker.stop()

# --- Resultados ---
print("\n=== Resultados ===")
print("Resultados para o sinal SEM ruído na entrada:")
print(f"PRD médio: {np.mean(prd_values):.2f}% ± {np.std(prd_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_values):.4f} ± {np.std(rmse_values):.4f}")
print("\nResultados para o sinal COM ruído (SNR = 40dB):")
print(f"PRD médio: {np.mean(prd_noisy_values):.2f}% ± {np.std(prd_noisy_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_noisy_values):.4f} ± {np.std(rmse_noisy_values):.4f}")
print("\nErros médios nas harmônicas (com ruído):")
for j, h in enumerate(harm):
    print(f"Harmônica {h}: {np.mean(harmonic_errors[:,j]):.2f}% ± {np.std(harmonic_errors[:,j]):.2f}%")

# --- Plotagem no formato do primeiro algoritmo ---
ruido_inserido = y_ruidoso - y

# 1. Sinal original
plt.figure(figsize=(12, 4))
plt.plot(t, y, label='Original', color='red')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# 2. Ruído inserido
plt.figure(figsize=(12, 4))
plt.plot(t, ruido_inserido, label='Ruído Inserido', color='gray')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Ruído Inserido no Sinal')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# 3. Sinal reconstruído
plt.figure(figsize=(12, 4))
plt.plot(t, reconstructed_noisy, label='Reconstruído com ruído', linestyle='--', color='blue')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title(f'Sinal Reconstruído (SL0 + DFT, CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# 4. Espectro original
freq = np.fft.fftfreq(N, Ts)[:N//2]
fft_y = 2/N * np.abs(np.fft.fft(y)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_y, label='Original', color='red')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# 5. Espectro reconstruído
fft_rec = 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_rec, '--', label='Reconstruído', color='blue')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Reconstruído')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

"""
# --- Visualização ---
plt.figure(figsize=(12,8))
plt.subplot(2,1,1)
plt.plot(t, y, label='Original')
plt.plot(t, y_ruidoso, alpha=0.6, label='Com ruído')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title('Sinal Original e com Ruído (SNR=40dB)')
plt.grid()

plt.subplot(2,1,2)
plt.plot(t, reconstructed_noisy, 'r--', label='Reconstruído (SL0 com DCT)')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title(f'Reconstrução com SL0 e DCT (CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.tight_layout()

# Espectro de frequência (DCT)
freq = np.arange(N//2) * (Fs/N)  # Frequências aproximadas para DCT
plt.figure(figsize=(12,6))
plt.plot(freq, np.abs(original_dct[:N//2]), label='Original (DCT)')
plt.plot(freq, np.abs(recon_dct[:N//2]), 'r--', label='SL0 (DCT)')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude (DCT)')
plt.title('Espectro de Frequência (DCT)')
plt.legend()
plt.grid()
#plt.show()
"""
# Print das emissões geradas
print(f'Emissões geradas pelo algoritmo de CS com DCT: {emissions} Kg')

"""# **Algoritmo SL0 com a dft**"""

import numpy as np
import matplotlib.pyplot as plt
from math import exp
from codecarbon import OfflineEmissionsTracker

# Iniciando o tracker de emissões <- CODECARBON
tracker = OfflineEmissionsTracker(country_iso_code="BRA", output_file='emissions_OMP_com_dft_3.csv')

# Funções de métrica
def calculate_prd(original, reconstructed):
    return np.sqrt(np.sum((original - reconstructed) ** 2)) / np.sqrt(np.sum(original ** 2)) * 100

def calculate_rmse(original, reconstructed):
    return np.sqrt(np.mean((original - reconstructed) ** 2))

# Implementação do SL0 (adaptada)
def sl0(A, y_compressed, sigma_min=0.1, sigma_decrease_factor=0.5, mu_0=2, L=1):
    """
    SL0 adaptado para seu sinal harmônico
    """
    A_pinv = np.linalg.pinv(A)
    s = A_pinv @ y_compressed
    sigma = 2.0 * np.abs(s).max()

    while sigma > sigma_min:
        for _ in range(L):
            delta = s * np.exp(-np.abs(s)**2 / sigma**2)
            s = s - mu_0 * delta
            s = s - A_pinv @ (A @ s - y_compressed)
        sigma *= sigma_decrease_factor

    return s

# --- Parâmetros do sinal ---
Fs = 10240
Ts = 1 / Fs
t = np.arange(Fs) * Ts
f = 60  # Frequência fundamental
harm = [1, 3, 7, 15, 27, 35, 45]  # Componentes harmônicas ímpares

# Geração do sinal original
y = np.sum([(1/h) * np.cos(2 * np.pi * h * f * t) for h in harm], axis=0)
original_dft = 2*np.abs(np.fft.fft(y))/len(y)

# Adição de ruído (SNR = 40dB)
SNR_dB = 40
ruido = np.random.normal(0, np.sqrt(np.var(y)/(10 ** (SNR_dB / 10))), len(y))
y_ruidoso = y + ruido

# --- Compressive Sensing ---
CR = 50  # Taxa de compressão (50%)
N = len(y)
M = int(N * (100 - CR) / 100)

# Matriz base DFT (normalizada)
F = np.fft.fft(np.eye(N)) / np.sqrt(N)

# Iniciando a medição das emissões
tracker.start()

# --- Experimento Principal ---
n_iterations = 5
prd_values = np.zeros(n_iterations)
rmse_values = np.zeros(n_iterations)
prd_noisy_values = np.zeros(n_iterations)
rmse_noisy_values = np.zeros(n_iterations)
harmonic_errors = np.zeros((n_iterations, len(harm)))

for i in range(n_iterations):
    print(f"Iteração {i+1}/{n_iterations}")

    # Seleciona amostras aleatórias
    samples = np.random.choice(N, M, replace=False)
    samples.sort()

    # Cria matriz de medição
    A = F[samples, :]
    clean_measurements = y[samples]
    noisy_measurements = y_ruidoso[samples]

    # Executa SL0 para medições limpas
    coeffs_clean = sl0(A, clean_measurements)
    reconstructed_clean = np.real(np.fft.ifft(coeffs_clean) * np.sqrt(N))
    reconstructed_clean *= np.max(y) / np.max(reconstructed_clean)  # Normalização

    # Executa SL0 para medições ruidosas
    coeffs_noisy = sl0(A, noisy_measurements)
    reconstructed_noisy = np.real(np.fft.ifft(coeffs_noisy) * np.sqrt(N))

    # Cálculo das métricas
    prd_values[i] = calculate_prd(y, reconstructed_clean)
    rmse_values[i] = calculate_rmse(y, reconstructed_clean)
    prd_noisy_values[i] = calculate_prd(y, reconstructed_noisy)
    rmse_noisy_values[i] = calculate_rmse(y, reconstructed_noisy)

    # Análise espectral
    recon_dft = 2*np.abs(np.fft.fft(reconstructed_noisy))/len(reconstructed_noisy)
    for j, h in enumerate(harm):
        idx_h = int(h * f / (Fs/N))
        harmonic_errors[i,j] = 100*np.abs(original_dft[idx_h]-recon_dft[idx_h])/original_dft[idx_h]

# Encerrando as leituras de emissões
emissions: float = tracker.stop()

# --- Resultados ---
print("\n=== Resultados ===")
print("Resultados para o sinal SEM ruído na entrada:")
print(f"PRD médio: {np.mean(prd_values):.2f}% ± {np.std(prd_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_values):.4f} ± {np.std(rmse_values):.4f}")
print("\nResultados para o sinal COM ruído (SNR = 40dB):")
print(f"PRD médio: {np.mean(prd_noisy_values):.2f}% ± {np.std(prd_noisy_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_noisy_values):.4f} ± {np.std(rmse_noisy_values):.4f}")
print("\nErros médios nas harmônicas (com ruído):")
for j, h in enumerate(harm):
    print(f"Harmônica {h}: {np.mean(harmonic_errors[:,j]):.2f}% ± {np.std(harmonic_errors[:,j]):.2f}%")

# --- Plotagem no formato do primeiro algoritmo ---
ruido_inserido = y_ruidoso - y

# 1. Sinal original
plt.figure(figsize=(12, 4))
plt.plot(t, y, label='Original', color='red')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# 2. Ruído inserido
plt.figure(figsize=(12, 4))
plt.plot(t, ruido_inserido, label='Ruído Inserido', color='gray')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title('Ruído Inserido no Sinal')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# 3. Sinal reconstruído
plt.figure(figsize=(12, 4))
plt.plot(t, reconstructed_noisy, label='Reconstruído com ruído', linestyle='--', color='blue')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.title(f'Sinal Reconstruído (SL0 + DFT, CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# 4. Espectro original
freq = np.fft.fftfreq(N, Ts)[:N//2]
fft_y = 2/N * np.abs(np.fft.fft(y)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_y, label='Original', color='red')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Original')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# 5. Espectro reconstruído
fft_rec = 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2])

plt.figure(figsize=(12, 4))
plt.plot(freq, fft_rec, '--', label='Reconstruído', color='blue')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência - Sinal Reconstruído')
plt.grid()
plt.legend()
plt.tight_layout()
#plt.show()

# Print das emissões geradas
print(f'Emissões geradas pelo algoritmo de CS: {emissions} Kg')

"""#**algoritmo sl0 + dct**"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.fftpack import dct, idct
from codecarbon import OfflineEmissionsTracker

# Iniciando o tracker de emissões <- CODECARBON
tracker = OfflineEmissionsTracker(country_iso_code="BRA", output_file='emissions_SL0_com_dct.csv')

# Funções de métrica
def calculate_prd(original, reconstructed):
    return np.sqrt(np.sum((original - reconstructed) ** 2)) / np.sqrt(np.sum(original ** 2)) * 100

def calculate_rmse(original, reconstructed):
    return np.sqrt(np.mean((original - reconstructed) ** 2))

# Implementação do SL0
def sl0(A, y_compressed, sigma_min=0.1, sigma_decrease_factor=0.5, mu_0=2, L=1):
    A_pinv = np.linalg.pinv(A)
    s = A_pinv @ y_compressed
    sigma = 2.0 * np.abs(s).max()

    while sigma > sigma_min:
        for _ in range(L):
            delta = s * np.exp(-np.abs(s)**2 / sigma**2)
            s = s - mu_0 * delta
            s = s - A_pinv @ (A @ s - y_compressed)
        sigma *= sigma_decrease_factor

    return s

# --- Parâmetros do sinal ---
Fs = 10240
Ts = 1 / Fs
t = np.arange(Fs) * Ts
f = 60
harm = [1, 3, 7, 15, 27, 35, 45]

# Sinal original
y = np.sum([(1/h) * np.cos(2*np.pi*h*f*t) for h in harm], axis=0)
original_dct = dct(y, norm='ortho')

# Adição de ruído
SNR_dB = 40
ruido = np.random.normal(0, np.sqrt(np.var(y)/(10 ** (SNR_dB/10))), len(y))
y_ruidoso = y + ruido

# --- Compressive Sensing ---
CR = 50
N = len(y)
M = int(N * (100 - CR) / 100)

# Matriz base DCT
F = dct(np.eye(N), norm='ortho')

# Iniciando emissões
tracker.start()

# --- Experimento ---
n_iterations = 1
prd_values = np.zeros(n_iterations)
rmse_values = np.zeros(n_iterations)
prd_noisy_values = np.zeros(n_iterations)
rmse_noisy_values = np.zeros(n_iterations)

for i in range(n_iterations):
    print(f"Iteração {i+1}/{n_iterations}")

    # Amostragem
    samples = np.random.choice(N, M, replace=False)
    samples.sort()

    # Matriz de medição
    A = F[samples, :]
    clean_measurements = y[samples]
    noisy_measurements = y_ruidoso[samples]

    # SL0 (limpo)
    coeffs_clean = sl0(A, clean_measurements)
    reconstructed_clean = idct(coeffs_clean, norm='ortho')

    # SL0 (ruidoso)
    coeffs_noisy = sl0(A, noisy_measurements)
    reconstructed_noisy = idct(coeffs_noisy, norm='ortho')

    # Métricas
    prd_values[i] = calculate_prd(y, reconstructed_clean)
    rmse_values[i] = calculate_rmse(y, reconstructed_clean)
    prd_noisy_values[i] = calculate_prd(y, reconstructed_noisy)
    rmse_noisy_values[i] = calculate_rmse(y, reconstructed_noisy)

# Encerrar emissões
emissions: float = tracker.stop()

# --- Resultados ---
print("\n=== Resultados ===")
print("SEM ruído:")
print(f"PRD médio: {np.mean(prd_values):.2f}% ± {np.std(prd_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_values):.4f} ± {np.std(rmse_values):.4f}")
print("\nCOM ruído (SNR = 40dB):")
print(f"PRD médio: {np.mean(prd_noisy_values):.2f}% ± {np.std(prd_noisy_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_noisy_values):.4f} ± {np.std(rmse_noisy_values):.4f}")

# --- Visualização ---
plt.figure(figsize=(12,8))
plt.subplot(2,1,1)
plt.plot(t, y, label='Original')
plt.plot(t, y_ruidoso, alpha=0.6, label='Com ruído')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title('Sinal Original e com Ruído')
plt.grid()

plt.subplot(2,1,2)
plt.plot(t, reconstructed_noisy, 'r--', label='Reconstruído (SL0 + DCT)')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title(f'Reconstrução (CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.tight_layout()
#plt.show()

# Espectro
freq = np.fft.fftfreq(N, Ts)[:N//2]
fft_y = 2/N * np.abs(np.fft.fft(y)[0:N//2])
fft_rec = 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2])

plt.figure(figsize=(12,6))
plt.plot(freq, fft_y, label='Original')
plt.plot(freq, fft_rec, 'r--', label='SL0 + DCT')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência')
plt.legend()
plt.grid()
#plt.show()

# Emissões
print(f'Emissões geradas pelo algoritmo de CS: {emissions} Kg')



"""#**SL0 + dct**

esse código está apresentando problemas
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.fftpack import dct, idct
from codecarbon import OfflineEmissionsTracker

# Iniciando o tracker de emissões <- CODECARBON
tracker = OfflineEmissionsTracker(country_iso_code="BRA", output_file='emissions_SL0_com_dct.csv')

# Funções de métrica
def calculate_prd(original, reconstructed):
    return np.sqrt(np.sum((original - reconstructed) ** 2)) / np.sqrt(np.sum(original ** 2)) * 100

def calculate_rmse(original, reconstructed):
    return np.sqrt(np.mean((original - reconstructed) ** 2))

# Implementação do SL0
def sl0(A, y_compressed, sigma_min=0.1, sigma_decrease_factor=0.5, mu_0=2, L=1):
    A_pinv = np.linalg.pinv(A)
    s = A_pinv @ y_compressed
    sigma = 2.0 * np.abs(s).max()

    while sigma > sigma_min:
        for _ in range(L):
            delta = s * np.exp(-np.abs(s)**2 / sigma**2)
            s = s - mu_0 * delta
            s = s - A_pinv @ (A @ s - y_compressed)
        sigma *= sigma_decrease_factor

    return s

# --- Parâmetros do sinal ---
Fs = 10240
Ts = 1 / Fs
t = np.arange(Fs) * Ts
f = 60
harm = [1, 3, 7, 15, 27, 35, 45]

# Sinal original
y = np.sum([(1/h) * np.cos(2*np.pi*h*f*t) for h in harm], axis=0)
original_dct = dct(y, norm='ortho')

# Adição de ruído
SNR_dB = 40
ruido = np.random.normal(0, np.sqrt(np.var(y)/(10 ** (SNR_dB/10))), len(y))
y_ruidoso = y + ruido

# --- Compressive Sensing ---
CR = 50
N = len(y)
M = int(N * (100 - CR) / 100)

# Matriz base DCT
F = dct(np.eye(N), norm='ortho')

# Iniciando emissões
tracker.start()

# --- Experimento ---
n_iterations = 5
prd_values = np.zeros(n_iterations)
rmse_values = np.zeros(n_iterations)
prd_noisy_values = np.zeros(n_iterations)
rmse_noisy_values = np.zeros(n_iterations)
harmonic_errors = np.zeros((n_iterations, len(harm)))  # <<< NOVO

for i in range(n_iterations):
    print(f"Iteração {i+1}/{n_iterations}")

    # Amostragem
    samples = np.random.choice(N, M, replace=False)
    samples.sort()

    # Matriz de medição
    A = F[samples, :]
    clean_measurements = y[samples]
    noisy_measurements = y_ruidoso[samples]

    # SL0 (limpo)
    coeffs_clean = sl0(A, clean_measurements)
    reconstructed_clean = idct(coeffs_clean, norm='ortho')

    # SL0 (ruidoso)
    coeffs_noisy = sl0(A, noisy_measurements)
    reconstructed_noisy = idct(coeffs_noisy, norm='ortho')

    # Métricas
    prd_values[i] = calculate_prd(y, reconstructed_clean)
    rmse_values[i] = calculate_rmse(y, reconstructed_clean)
    prd_noisy_values[i] = calculate_prd(y, reconstructed_noisy)
    rmse_noisy_values[i] = calculate_rmse(y, reconstructed_noisy)

    # --- Análise espectral para erros por harmônica ---
    recon_dct = dct(reconstructed_noisy, norm='ortho')
    for j, h in enumerate(harm):
        idx_h = int(h * f / (Fs/N))  # índice da harmônica
        harmonic_errors[i, j] = 100 * np.abs(original_dct[idx_h] - recon_dct[idx_h]) / original_dct[idx_h]

# Encerrar emissões
emissions: float = tracker.stop()

# --- Resultados ---
print("\n=== Resultados ===")
print("SEM ruído:")
print(f"PRD médio: {np.mean(prd_values):.2f}% ± {np.std(prd_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_values):.4f} ± {np.std(rmse_values):.4f}")
print("\nCOM ruído (SNR = 40dB):")
print(f"PRD médio: {np.mean(prd_noisy_values):.2f}% ± {np.std(prd_noisy_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_noisy_values):.4f} ± {np.std(rmse_noisy_values):.4f}")

print("\nErros médios nas harmônicas (com ruído):")  # <<< NOVO
for j, h in enumerate(harm):
    print(f"Harmônica {h}: {np.mean(harmonic_errors[:,j]):.2f}% ± {np.std(harmonic_errors[:,j]):.2f}%")

# --- Visualização ---
plt.figure(figsize=(12,8))
plt.subplot(2,1,1)
plt.plot(t, y, label='Original')
plt.plot(t, y_ruidoso, alpha=0.6, label='Com ruído')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title('Sinal Original e com Ruído')
plt.grid()

plt.subplot(2,1,2)
plt.plot(t, reconstructed_noisy, 'r--', label='Reconstruído (SL0 + DCT)')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.title(f'Reconstrução (CR={CR}%, PRD={np.mean(prd_noisy_values):.2f}%)')
plt.grid()
plt.tight_layout()
#plt.show()

# Espectro
freq = np.fft.fftfreq(N, Ts)[:N//2]
fft_y = 2/N * np.abs(np.fft.fft(y)[0:N//2])
fft_rec = 2/N * np.abs(np.fft.fft(reconstructed_noisy)[0:N//2])

plt.figure(figsize=(12,6))
plt.plot(freq, fft_y, label='Original')
plt.plot(freq, fft_rec, 'r--', label='SL0 + DCT')
for h in harm:
    plt.axvline(h*f, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.title('Espectro de Frequência')
plt.legend()
plt.grid()
#plt.show()

# Emissões
print(f'Emissões geradas pelo algoritmo de CS: {emissions} Kg')

import numpy as np
from math import exp

# --- Funções de métrica ---
def calculate_prd(original, reconstructed):
    return np.sqrt(np.sum((original - reconstructed) ** 2)) / np.sqrt(np.sum(original ** 2)) * 100

def calculate_rmse(original, reconstructed):
    return np.sqrt(np.mean((original - reconstructed) ** 2))

# --- Implementação SL0 otimizada (FFT implícita) ---
def sl0_implicit(y_compressed, sigma_min=0.1, sigma_decrease_factor=0.5, mu_0=2, L=1):
    """
    Versão otimizada do SL0 que usa a base DFT de forma implícita (sem montar matriz NxN).
    """
    N = len(y)  # tamanho original do sinal
    M = len(y_compressed)

    # reconstrução inicial
    coeffs = np.fft.fft(y) / np.sqrt(N)
    s = coeffs.copy()

    sigma = 2.0 * np.abs(s).max()

    while sigma > sigma_min:
        for _ in range(L):
            delta = s * np.exp(-np.abs(s) ** 2 / sigma ** 2)
            s = s - mu_0 * delta
        sigma *= sigma_decrease_factor

    return s

# --- Parâmetros do sinal ---
Fs = 10240
Ts = 1 / Fs
t = np.arange(Fs) * Ts
f = 60  # Frequência fundamental
harm = [1, 3, 7, 15, 27, 35, 45]  # Harmônicas ímpares

# Geração do sinal original
y = np.sum([(1/h) * np.cos(2 * np.pi * h * f * t) for h in harm], axis=0)
original_dft = (2/len(y)) * np.abs(np.fft.fft(y))

# Adição de ruído (SNR = 40dB)
SNR_dB = 40
ruido = np.random.normal(0, np.sqrt(np.var(y)/(10 ** (SNR_dB / 10))), len(y))
y_ruidoso = y + ruido

# --- Compressive Sensing ---
CR = 50  # Taxa de compressão
N = len(y)
M = int(N * (100 - CR) / 100)

# --- Número de execuções ---
n_iterations = 5

# Arrays para armazenar métricas
prd_values = np.zeros(n_iterations)
rmse_values = np.zeros(n_iterations)
prd_noisy_values = np.zeros(n_iterations)
rmse_noisy_values = np.zeros(n_iterations)
harmonic_errors = np.zeros((n_iterations, len(harm)))

for i in range(n_iterations):
    print(f"Iteração {i+1}/{n_iterations}")

    # Amostras aleatórias
    samples = np.random.choice(N, M, replace=False)
    samples.sort()

    # --- SEM RUÍDO ---
    y_samples_clean = y[samples]
    coeffs_clean = sl0_implicit(y_samples_clean)
    rec_clean = np.real(np.fft.ifft(coeffs_clean) * np.sqrt(N))
    prd_values[i] = calculate_prd(y, rec_clean)
    rmse_values[i] = calculate_rmse(y, rec_clean)

    # --- COM RUÍDO ---
    y_samples_noisy = y_ruidoso[samples]
    coeffs_noisy = sl0_implicit(y_samples_noisy)
    rec_noisy = np.real(np.fft.ifft(coeffs_noisy) * np.sqrt(N))
    prd_noisy_values[i] = calculate_prd(y, rec_noisy)
    rmse_noisy_values[i] = calculate_rmse(y, rec_noisy)

    # erros por harmônica (no sinal com ruído)
    recon_dft = (2/N) * np.abs(np.fft.fft(rec_noisy))
    for j, h in enumerate(harm):
        idx_h = int(h * f / (Fs/N))
        harmonic_errors[i,j] = 100*np.abs(original_dft[idx_h]-recon_dft[idx_h])/original_dft[idx_h]

# --- Resultados ---
print("\n=== Resultados ===")
print("Resultados para o sinal SEM ruído na entrada:")
print(f"PRD médio: {np.mean(prd_values):.2f}% ± {np.std(prd_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_values):.4f} ± {np.std(rmse_values):.4f}")

print("\nResultados para o sinal COM ruído (SNR = 40dB):")
print(f"PRD médio: {np.mean(prd_noisy_values):.2f}% ± {np.std(prd_noisy_values):.2f}%")
print(f"RMSE médio: {np.mean(rmse_noisy_values):.4f} ± {np.std(rmse_noisy_values):.4f}")

print("\nErros médios nas harmônicas (com ruído):")
for j, h in enumerate(harm):
    print(f"Harmônica {h}: {np.mean(harmonic_errors[:,j]):.4f} ± {np.std(harmonic_errors[:,j]):.4f}")

import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft, ifft

# --- Funções de métrica ---
def calcular_prd(original, reconstruido):
    return np.sqrt(np.sum((original - reconstruido) ** 2)) / np.sqrt(np.sum(original ** 2)) * 100

def calcular_rmse(original, reconstruido):
    return np.sqrt(np.mean((original - reconstruido) ** 2))

# --- Parâmetros do sinal ---
frequencia_amostragem = 10240
periodo_amostragem = 1 / frequencia_amostragem
tempo = np.arange(frequencia_amostragem) * periodo_amostragem
frequencia_fundamental = 60
N = len(tempo)

# Harmônicas do sinal
harmonicas = [1, 3, 7, 15, 27, 35, 45]
amplitudes = [1, 1/3, 1/7, 1/15, 1/27, 1/35, 1/45]

# Sinal original e ruidoso
sinal_original = np.sum([amplitudes[i] * np.cos(2*np.pi*h*frequencia_fundamental*tempo)
                         for i, h in enumerate(harmonicas)], axis=0)

SNR_dB = 40
np.random.seed(42)
ruido = np.random.normal(0, np.sqrt(np.var(sinal_original)/(10**(SNR_dB/10))), N)
sinal_ruidoso = sinal_original + ruido

# --- Reconstrução com parâmetros estatísticos (magnitude) ---
num_coeficientes_a_manter = 2 * len(harmonicas) # Mantenha o dobro do número de harmônicas para cobrir frequências positivas e negativas

# 1. Aplicar a FFT no sinal ruidoso
coeficientes_fft = fft(sinal_ruidoso)

# 2. Identificar e manter os coeficientes com maior magnitude
indices_maiores = np.argsort(np.abs(coeficientes_fft))[-num_coeficientes_a_manter:]

# 3. Criar uma nova matriz de coeficientes, zerando os menos importantes
coeficientes_filtrados = np.zeros(N, dtype=complex)
coeficientes_filtrados[indices_maiores] = coeficientes_fft[indices_maiores]

# 4. Aplicar a IFFT para reconstruir o sinal
sinal_reconstruido = ifft(coeficientes_filtrados).real

# --- Análise e Visualização ---
print("="*50)
print("Análise de Reconstrução com FFT")
print("="*50)
print(f"PRD: {calcular_prd(sinal_original, sinal_reconstruido):.2f}%")
print(f"RMSE: {calcular_rmse(sinal_original, sinal_reconstruido):.6f}")

plt.figure(figsize=(15, 12))

# 1. Sinais no domínio do tempo (Primeiros 1000 pontos para clareza)
plt.subplot(3, 1, 1)
plt.plot(tempo[:1000], sinal_ruidoso[:1000], 'k-', alpha=0.7, label='Sinal Ruidoso')
plt.plot(tempo[:1000], sinal_reconstruido[:1000], 'r--', linewidth=2, label='Sinal Reconstruído')
plt.plot(tempo[:1000], sinal_original[:1000], 'b-.', linewidth=1, label='Sinal Original')
plt.title('Sinais no Domínio do Tempo')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.grid(True)

# 2. Espectro de frequência (apenas a parte positiva)
frequencias = np.fft.fftfreq(N, periodo_amostragem)[:N//2]
magnitude_fft_original = 2/N * np.abs(fft(sinal_original)[0:N//2])
magnitude_fft_ruidoso = 2/N * np.abs(coeficientes_fft[0:N//2])
magnitude_fft_reconstruido = 2/N * np.abs(coeficientes_filtrados[0:N//2])

plt.subplot(3, 1, 2)
plt.plot(frequencias, magnitude_fft_ruidoso, 'k-', alpha=0.7, label='Espectro Ruidoso')
plt.plot(frequencias, magnitude_fft_reconstruido, 'r--', linewidth=2, label='Espectro Reconstruído')
plt.plot(frequencias, magnitude_fft_original, 'b-.', linewidth=1, label='Espectro Original')
for h in harmonicas:
    plt.axvline(h*frequencia_fundamental, color='gray', linestyle=':', alpha=0.5)
plt.xlim(0, 3000)
plt.title('Espectro de Frequência (Análise de Conteúdo)')
plt.xlabel('Frequência (Hz)')
plt.ylabel('Magnitude')
plt.legend()
plt.grid(True)

# 3. Erro de reconstrução
erro = sinal_original - sinal_reconstruido
plt.subplot(3, 1, 3)
plt.plot(tempo, erro, 'g-', alpha=0.7)
plt.title('Erro de Reconstrução (Original - Reconstruído)')
plt.xlabel('Tempo (s)')
plt.ylabel('Amplitude do Erro')
plt.grid(True)

plt.tight_layout()
plt.show()